[package]
name = "lighthouse-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.18"
tokio = { version = "1", features = ["full"] }
rand = "0.8"
futures = "0.3"
serde_array_query = "0.3.0"
serde = { version = "1", features = ["derive"] }
warp = "0.3"
